name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  PROJECT: kapwing-dev
  IMAGE_REPOSITORY: us-east1-docker.pkg.dev/kapwing-dev/gentle-transcription-service/gentle-image
  USE_GKE_GCLOUD_AUTH_PLUGIN: true

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: "gcp_auth"
        uses: "./.github/actions/gcp-auth"

      - name: helper
        run: gcloud auth configure-docker us-east1-docker.pkg.dev -q

      - name: Download models
        run: gsutil cp -r gs://kapwing-useast1/mlmodels/exp .

      - name: Pull existing Docker image
        run: docker pull ${IMAGE_REPOSITORY}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${IMAGE_REPOSITORY}

      - name: Push the Docker image
        run: docker push ${IMAGE_REPOSITORY}

      - name: Reassign Gentle transcription service to new Docker image
        run: gcloud run services update gentle-transcription-service --image=${IMAGE_REPOSITORY}
